### ISSUE TITLE
error when installing tg_partner_firstname on odoo v8

### ISSUE THREAD

**Issue by kihiuho** [itpp-labs/pos-addons#1]
OpenERP Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 495, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 308, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 685, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 360, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 987, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 975, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 322, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 984, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 1070, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 937, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 855, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1024, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 270, in create
    context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 204, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 297, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3900, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 202, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 429, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4091, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 202, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1261, in _validate_fields
    raise except_orm('ValidateError', '\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `country` does not exist

Error context:
View `view.tg.partner.tree`
[view_id: 1128, xml_id: n/a, model: res.partner, parent_id: 124]" while parsing /opt/odoo/custom/addons/tg_partner_firstname/tg_partner_view.xml:30, near
<record model="ir.ui.view" id="view_tg_partner_tree">
            <field name="model">res.partner</field>
            <field name="name">view.tg.partner.tree</field>
            <field name="view_type">tree</field>
            <field name="inherit_id" ref="base.view_partner_tree"/>
            <field name="arch" type="xml">
                <data><field name="display_name" position="after">
                    <field name="firstname"/>
                    <field name="zip"/>
                </field>
                <field name="phone" position="after">
                    <field name="mobile"/>
                </field>
                <field name="email" position="after">  
                    <field name="country"/>
                </field>
            </data></field>
        </record>

**Comment by yelizariev** [comment]
Hello! Thanks for reporting.

I didn't test this module for 8.0 branch, so errors are possible. I will fix it when I need to use this addon for v8.

**Comment by ezerouali** [comment]
Seems like adding the missing field to “tg_partner_firstname.py”, fixes the installation issue … then, accessing the POS works, but no products are shown or just hangs when entering.

**Comment by yelizariev** [comment]
@makwin have you fixed it? Could you make pull request?

**Comment by kesturbo** [comment]
Hello @yelizariev , did you succeeded with issues about  "Field `country` does not exist " ?
