### ISSUE TITLE
pos_partner_sync 12.0 issue

### ISSUE THREAD

**Issue by Ramil-Mukhametzyanov** [itpp-labs/pos-addons#1240]
Odoo 12.0
1. Install pos_parnter_sync
2. Install Contact
3. Create 2 POSs
4. Open POS by Demo, open Customer list, open a customer details
5. Delete a contact by Admin
Result: error in the Demo screen

**Comment by Ramil-Mukhametzyanov** [comment]
Odoo 12.0
1. Install pos_parnter_sync
2. Install Contact
3. Create 2 POS
4. Open POS by Demo, open Customer list, open a customer details
5. Delete a contact by Admin
Result: error in the Demo screen

Longpolling Handling Error remove_unlinked_partners/<@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_partner_sync/static/src/js/pos_partner_sync.js:107:21 
_.forEach@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/underscore/underscore.js:145:9 
remove_unlinked_partners@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_partner_sync/static/src/js/pos_partner_sync.js:105:15 
on_barcode_updates@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_partner_sync/static/src/js/pos_partner_sync.js:28:26 
on_notification_do@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_longpolling/static/src/js/longpolling.js:111:32 
on_notification_callback@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_longpolling/static/src/js/longpolling.js:95:22 
trigger@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/src/js/core/mixins.js:225:31 
trigger@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/src/js/core/mixins.js:329:42 
_onPoll@http://02586-12-0-cc423b-base.runbot.it-projects.info/bus/static/src/js/longpolling_bus.js:243:14 
_onPoll@http://02586-12-0-cc423b-base.runbot.it-projects.info/bus/static/src/js/crosstab_bus.js:282:27 
OdooClass.extend/</prototype[name]</<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/src/js/core/class.js:90:38 
_poll/<@http://02586-12-0-cc423b-base.runbot.it-projects.info/pos_longpolling/static/src/js/longpolling_bus.js:28:22 
then/</</<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3276:89 
fire@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3119:58 
fireWith@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3231:49 
Deferred/</deferred[tuple[0]]@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3321:62 
rpc/<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/src/js/services/ajax_service.js:16:29 
then/</</<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3276:89 
fire@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3119:58 
fireWith@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3231:49 
Deferred/</deferred[tuple[0]]@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3321:62 
fire@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3119:58 
fireWith@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3231:49 
Deferred/</deferred[tuple[0]]@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3321:62 
genericJsonRpc/<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/src/js/core/ajax.js:65:18 
then/</</<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3276:89
 fire@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3119:58 
 fireWith@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3231:49 
 then/</</<@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3283:104 
fire@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3119:58 
fireWith@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:3231:49 
done@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:9275:42 
callback@http://02586-12-0-cc423b-base.runbot.it-projects.info/web/static/lib/jquery/jquery.js:9685:57




Longpolling Handling Error TypeError: Cannot read property 'barcode' of undefined    at http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/559-10cf043/point_of_sale.assets.js:504:239   
 at Function._.each._.forEach (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/539-67c16e1/web.assets_common.js:12:558)    
 at child.remove_unlinked_partners (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/559-10cf043/point_of_sale.assets.js:504:168)    
 at child.on_barcode_updates (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/559-10cf043/point_of_sale.assets.js:500:726)    
 at Class.on_notification_do (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/559-10cf043/point_of_sale.assets.js:464:8)    
 at Class.on_notification_callback (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/559-10cf043/point_of_sale.assets.js:461:421)    
 at Class.trigger (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/539-67c16e1/web.assets_common.js:3641:180)    
 a t Class.trigger (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/539-67c16e1/web.assets_common.js:3647:148)    
 at Class._onPoll (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/570-6caad41/point_of_sale.pos_assets_backend.js:2351:45)    
 at Class._onPoll (http://02586-12-0-cc423b-base.runbot.it-projects.info/web/content/570-6caad41/point_of_sale.pos_assets_backend.js:2366:481)
