### ISSUE TITLE
ImportError: cannot import name api

### ISSUE THREAD

**Issue by rjay1018** [itpp-labs/pos-addons#22]
2015-10-12 09:38:22,312 4962 INFO ? werkzeug: 127.0.0.1 - - [12/Oct/2015 09:38:22] "GET /web/login?redirect=http%3A%2F%2Fv8.myerp.ph%2Fweb%3Fdb%3Dtest HTTP/1.1" 500 -
2015-10-12 09:38:22,319 4962 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/v8/server/openerp/service/server.py", line 273, in app
    return self.app(e, s)
  File "/opt/odoo/v8/server/openerp/service/wsgi_server.py", line 215, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/v8/server/openerp/service/wsgi_server.py", line 201, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/v8/server/openerp/http.py", line 1096, in **call**
    self.load_addons()
  File "/opt/odoo/v8/server/openerp/http.py", line 1115, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/odoo/v8/server/openerp/modules/module.py", line 72, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/v8/extra-addons/pos_debranding/**init**.py", line 1, in <module>
    import models
  File "/opt/odoo/v8/extra-addons/pos_debranding/models.py", line 2, in <module>
    from openerp import api, models, fields, SUPERUSER_ID
ImportError: cannot import name api

**Comment by yelizariev** [comment]
Are you sure that you use odoo version 8?

**Comment by rjay1018** [comment]
I downloaded the latest odoo version 8 and it worked. Thank You
