### ISSUE TITLE
POS Debt Notebook - Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by jayo2005** [itpp-labs/pos-addons#228]
After  installing POS Debt notebook on version 10, I can not Tender with the Cash button. The Debt button works. When I press the Cash button and then Validate
![debterror](https://cloud.githubusercontent.com/assets/7015925/22609881/d171a72e-ea5a-11e6-92e0-92d3067157ac.PNG)
 I get the below error

```
Uncaught TypeError: Cannot read property 'id' of null
http://192.168.1.125:8069/web/content/714-620a105/point_of_sale.assets.js:465
Traceback:
TypeError: Cannot read property 'id' of null
    at Class.validate_order (http://192.168.1.125:8069/web/content/714-620a105/point_of_sale.assets.js:465:73)
    at Class.validate_order (http://192.168.1.125:8069/web/content/683-66a70ca/web.assets_common.js:3012:371)
    at HTMLSpanElement.<anonymous> (http://192.168.1.125:8069/web/content/714-620a105/point_of_sale.assets.js:359:856)
    at HTMLSpanElement.dispatch (http://192.168.1.125:8069/web/content/683-66a70ca/web.assets_common.js:637:451)
    at HTMLSpanElement.$event.dispatch (http://192.168.1.125:8069/web/content/714-620a105/point_of_sale.assets.js:434:18)
    at HTMLSpanElement.elemData.handle (http://192.168.1.125:8069/web/content/683-66a70ca/web.assets_common.js:610:173)
```

**Comment by yelizariev** [comment]
Thanks for reporting. Try this update:
https://github.com/it-projects-llc/pos-addons/pull/229

**Comment by jayo2005** [comment]
Works now. Thanks
