### ISSUE TITLE
error while installing Custom pos session report (2)    on odoo ver 10

### ISSUE THREAD

**Issue by kozakos** [itpp-labs/pos-addons#238]
error while installing Custom pos session report (2)   on odoo ver 10

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 327, in init_models
    models[0].recompute()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5287, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5287, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5186, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 955, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 928, in _compute_value
    self.compute(records)
TypeError: _get_sum_entry_encoding_take_out() takes at least 6 arguments (1 given)

**Comment by yelizariev** [comment]
As you can at [manifest](https://github.com/it-projects-llc/pos-addons/blob/10.0/pos_session_custom2/__openerp__.py#L23) the module is not ported to 10.0 yet

**Comment by jujes** [comment]
¬¬
here the same issue... 

![screenshot-www odoo com-2017-03-24-21-02-45](https://cloud.githubusercontent.com/assets/2881017/24311679/8339718a-10d5-11e7-816e-32b0cd300d6c.png)

**Comment by yelizariev** [comment]
The problem is that odoo app store doesn't remove the module if one was available without ``installable: True`` at least once.
We used to merging branches without checking ``installable`` attribute and got such issues

**Comment by webtense** [comment]
Are there alternatives to this report for Odoo10?
