### ISSUE TITLE
POS Debt Notebook on odoo 9 error

### ISSUE THREAD

**Issue by akhif4u** [itpp-labs/pos-addons#254]
Error on selecting pos config 

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1563, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 927, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 470, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `debt_dummy_product_id` does not exist

Error context:
View `pos.config.form.view`
[view_id: 697, xml_id: point_of_sale.view_pos_config_form, model: pos.config, parent_id: n/a]

**Comment by dansalsero** [comment]
Hi, this means that the module is not correctly installed.

You can remove the debt_dummy_product_id field from the view, update the module and then add the field again.

Daniel.
