### ISSUE TITLE
[10.0-pos_multi_session] Error on each update

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#338]
Each time I update a product (add it or delete it) on POS-A, even though I get the update on POS-B an error arises with each update: 

```
point_of_sale.assets.js:726 Uncaught TypeError: Cannot read property 'id' of null
    at child.ms_on_update (http://supereconomico.iterativo.do/web/content/653-338ccf1/point_of_sale.assets.js:726:22)
    at http://supereconomico.iterativo.do/web/content/653-338ccf1/point_of_sale.assets.js:718:71
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (http://supereconomico.iterativo.do/web/content/653-338ccf1/point_of_sale.assets.js:718:39)
    at fire (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:548:56)
    at fire (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:546:198)
    at Object.<anonymous> (http://supereconomico.iterativo.do/web/content/445-4fc1de6/web.assets_common.js:547:874)
```

This is the failing code line:
`            if (order && order.table.id != data.table_id) {`

**Comment by yelizariev** [comment]
It seems that your POS-A and POS-B don't have the same floors or don't have floors at all. 
We have a plan to improve it and allows set floors for POS at a single place (pos multi sesssion model)

**Comment by yelizariev** [comment]
Workaround: 
* close all sessions
* set the same floors for POSes

**Comment by gustavovalverde** [comment]
Worked with workaround. I'll close it. If you'd like to keep it open just to have a better error handling for this, that's your call.
