### ISSUE TITLE
[10.0 - POS Debt Notebook]: Can't close the POS session after making returns

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#357]
A return was made in the POS, this returned order is causing this issue: 

```
2017-08-18 11:57:47,373 7893 INFO client odoo.sql_db: bad query: INSERT INTO "account_payment" ("id", "move_type", "name", "payment_date", "communication", "payment_difference_handling", "journal_id", "move_name", "currency_id", "partner_type", "amount", "state", "payment_type", "partner_id", "payment_method_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_payment_id_seq'), 'auto', 'POS/2017/08/17/21', '2017-08-17', 'Cafeteria AASE/0438: ', 'open', 20, NULL, 74, 'supplier', 65.0, 'reconciled', 'outbound', 103152, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-08-18 11:57:47,377 7893 DEBUG client odoo.service.model: IntegrityError
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 246, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 265, in action_pos_session_close
    st.with_context(ctx).sudo().button_confirm_bank()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 238, in button_confirm_bank
    st_line.fast_counterpart_creation()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 831, in fast_counterpart_creation
    st_line.process_reconciliation(new_aml_dicts=[vals])
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 932, in process_reconciliation
    'name': self.statement_id.name,
  File "/odoo/odoo-server/src/odoo/addons/payment/models/account_payment.py", line 34, in create
    account_payment = super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/custom/dominican_addons/advanced_payment/models/account_payment.py", line 693, in create
    return super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/odoo/addons/account_check_printing/models/account_payment.py", line 89, in create
    return super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "payment_method_id" violates not-null constraint
DETAIL:  Failing row contains (2213, 2017-08-18 11:57:40.616816, Cafeteria AASE/0438: , 20, 74, 103152, null, 2017-08-17, open, null, reconciled, null, 1, null, supplier, 2017-08-18 11:57:40.616816, 1, POS/2017/08/17/21, null, 65.0, outbound, null, null, null, null, null, null, null, null, auto, null).
```

How could I temporarily fix this? 

Regards,

**Comment by gustavovalverde** [comment]
Additionally, the credit is not being refunded when doing products return.

**Comment by yelizariev** [comment]
Can it be related to third-party module ``advanced_payment``?
Because I cannot reproduce both issues. Can you send steps to reproduce it on fresh database?

**Comment by gustavovalverde** [comment]
I'll try to do it without third-party modules, as I'm using https://apps.odoo.com/apps/modules/10.0/pos_order_return/ to do returns/refunds. 

But I removed advanced_payment and it's practically the same:
```
2017-08-23 11:08:12,110 1329 INFO client odoo.sql_db: bad query: INSERT INTO "account_payment" ("id", "payment_date", "name", "communication", "payment_difference_handling", "journal_id", "move_name", "currency_id", "partner_type", "state", "payment_type", "amount", "partner_id", "payment_method_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_payment_id_seq'), '2017-08-17', 'POS/2017/08/17/21', 'Cafeteria AASE/0438: ', 'open', 20, NULL, 74, 'supplier', 'reconciled', 'outbound', 65.0, 103152, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
2017-08-23 11:08:12,111 1329 DEBUG client odoo.service.model: IntegrityError
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 246, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/odoo/odoo-server/src/odoo/addons/point_of_sale/models/pos_session.py", line 265, in action_pos_session_close
    st.with_context(ctx).sudo().button_confirm_bank()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 238, in button_confirm_bank
    st_line.fast_counterpart_creation()
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 831, in fast_counterpart_creation
    st_line.process_reconciliation(new_aml_dicts=[vals])
  File "/odoo/odoo-server/src/odoo/addons/account/models/account_bank_statement.py", line 932, in process_reconciliation
    'name': self.statement_id.name,
  File "/odoo/odoo-server/src/odoo/addons/payment/models/account_payment.py", line 34, in create
    account_payment = super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/odoo/addons/account_check_printing/models/account_payment.py", line 89, in create
    return super(AccountPayment, self).create(vals)
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/src/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "payment_method_id" violates not-null constraint
DETAIL:  Failing row contains (4326, 2017-08-23 11:08:07.213642, Cafeteria AASE/0438: , 20, 74, 103152, null, 2017-08-17, open, null, reconciled, null, 1, null, supplier, 2017-08-23 11:08:07.213642, 1, POS/2017/08/17/21, null, 65.0, outbound, null, null, null, null, null, null, null, null).

```

**Comment by yelizariev** [comment]
How do you make refunds? Via POS? Do you select Debt Journal when refund?

**Comment by gustavovalverde** [comment]
Ok, so after making a few tests with different journals and scenarios, let me summarize:
- The credit is being returned to the client, the confusion is caused because `debt_after` label does not consider the refund scenario, so it's not showing that the credit is being refunded instead of being taken.
- All refunds with other type of journals (Cash, Bank) are working and the POS Session can be closed, but when using the _debt journal_ it shows the error, just after clicking to validate the POS Session.

This is solely using refunds in the POS with https://apps.odoo.com/apps/modules/10.0/pos_order_return/

**Comment by gustavovalverde** [comment]
@yelizariev I've pinpoint the issue. It's actually an issue on Odoo's core: https://github.com/odoo/odoo/issues/19086

P.S.: This happened as I didn't use the default journal created by your module, but instead used one already being used with this configuration.
