### ISSUE TITLE
Canceled Lines Error when update 

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#381]
Hello, the error comes today.
after i have update to the latest code plz help 
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in call
return self.method(*args, **kw)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
response = f(*args, **kw)
File "/home/odoo/en-addons/web/controllers/main.py", line 862, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/home/odoo/en-addons/web/controllers/main.py", line 854, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 687, in call_kw
return call_kw_model(method, model, args, kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_model
result = method(recs, *args, **kwargs)
File "/home/odoo/en-addons/pos_loyalty/models/pos_order.py", line 20, in create_from_ui
order_ids = super(PosOrder, self).create_from_ui(orders)
File "/home/odoo/en-addons/point_of_sale/models/pos_order.py", line 510, in create_from_ui
pos_order = self._process_order(order)
File "/home/odoo/pos-addons/pos_order_cancel/models/models.py", line 34, in _process_order
order.cancellation_reason = pos_order['CancellationReason'].encode('utf-8').strip(" \t
")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 26: ordinal not in range(128)
plz help
![29808234-6f48cb86-8cc1-11e7-8485-55b3b5f1ff79](https://user-images.githubusercontent.com/8590556/30050631-5e35025a-9249-11e7-8b7c-2fc6391b7b1a.jpg)
![29808251-7d5a4eac-8cc1-11e7-9662-9d06464b7e2a](https://user-images.githubusercontent.com/8590556/30050633-5e580746-9249-11e7-9259-b5b1cc7b97d1.jpg)

**Comment by 360org** [comment]
Hello i need help this is new error
Uncaught TypeError: Cannot read property 'orderlines' of undefined
http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:585
Traceback:
TypeError: Cannot read property 'orderlines' of undefined
    at http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:44:599
    at Function._.each._.forEach (http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:12:558)
    at child.ms_do_update (http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:44:538)
    at child.ms_on_update (http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:580:51)
    at child.ms_on_update (http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:667:38)
    at http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:621:71
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:621:39)
    at fire (http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:546:198)

**Comment by 360org** [comment]
TypeError: null is not an object (evaluating 'order.table.id')
http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:666
Traceback:
ms_on_update@http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:666:22
http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:621:83
forEach@[native code]
http://gardenvungtau.com/web/content/3138-b805e53/point_of_sale.assets.js:621:46
fire@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:541:304
fireWith@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:546:202
http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:548:56
fire@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:541:304
fireWith@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:546:202
http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:547:874
fire@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:541:304
fireWith@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:546:202
http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:547:874
fire@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:541:304
fireWith@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:546:202
done@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:937:106
callback@http://gardenvungtau.com/web/content/1924-909e778/web.assets_common.js:957:23

**Comment by gustavovalverde** [comment]
I'm also experiencing the same error in https://github.com/it-projects-llc/pos-addons/issues/381#issuecomment-328313829

After this error, there's commonly inconsistency between one POS and the other, as a line was removed but it wasn't in the other one. And also, after getting the error in one POS it might stop receiving updates for a while, or starts getting the error if products are added to the same order that got a product removed.

**Comment by gustavovalverde** [comment]
And having: 
![image](https://user-images.githubusercontent.com/16890942/30950014-efdc6054-a3e7-11e7-9dfb-b291069cffab.png)

With no traceback on the console

**Comment by ilmir-k** [comment]
Hi guys,

We made updates in pos_multi_session_restaurant, pos_order_cancel_restaurant modules and its dependencies that should fix the issues you faced. Please take the latest updates.
Note that we don't use the technical module pos_multi_session_restaurant_cancel_order anymore, which provided the compatibility of these modules, so you can remove it.

**Comment by gustavovalverde** [comment]
I'm supposing this can be closed after https://github.com/it-projects-llc/pos-addons/pull/414

**Comment by ilmir-k** [comment]
We think yes, thanks
