### ISSUE TITLE
undefined Client Error

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#401]
undefined Client Error

Uncaught TypeError: Cannot read property 'id' of null
http://mocrestaurant.vn/web/content/2807-66b684f/point_of_sale.assets.js:632
Traceback:
TypeError: Cannot read property 'id' of null
    at http://mocrestaurant.vn/web/content/2807-66b684f/point_of_sale.assets.js:632:973
    at Array.find (native)
    at Object.<anonymous> (http://mocrestaurant.vn/web/content/2807-66b684f/point_of_sale.assets.js:632:923)
    at Object.<anonymous> (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:547:681)
    at fire (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:548:56)
    at fire (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) [as resolve] (http://mocrestaurant.vn/web/content/2713-54cadf6/web.assets_common.js:548:56)

**Comment by GabbasovDinar** [comment]
@W360S, I think you need to update the odoo

**Comment by 360org** [comment]
i have update latest odoo.

**Comment by 360org** [comment]
it still show error

**Comment by yelizariev** [comment]
@W360S could you reproduce error in developer mode (/pos/web?debug=assets) and send log again.

**Comment by 360org** [comment]
ok, sorry i have busy for few days.
