### ISSUE TITLE
LINE 1: ...d" ("id", "user_id", "canceled_date", "order_id", "current_q...                                                              ^

### ISSUE THREAD

**Issue by 360org** [itpp-labs/pos-addons#434]
Hello, the error come when i try to upgrade system plz help

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/en-addons/en20170910/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/en-addons/en20170910/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/en-addons/en20170910/point_of_sale/models/pos_order.py", line 551, in create_from_ui
    pos_order = self._process_order(order)
  File "/home/odoo/pos-addons/pos_order_cancel/models/models.py", line 55, in _process_order
    order = super(PosOrder, self)._process_order(pos_order)
  File "/home/odoo/en-addons/en20170910/point_of_sale/models/pos_order.py", line 111, in _process_order
    order = self.create(self._order_fields(pos_order))
  File "/home/odoo/en-addons/en20170910/point_of_sale/models/pos_order.py", line 456, in create
    return super(PosOrder, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3983, in _create
    field.write(self.with_context(rel_context), vals[name])
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 2175, in write
    comodel.create(act[2])
  File "/home/odoo/pos-addons/pos_order_cancel/models/models.py", line 138, in create
    return super(PosOrderLineCanceled, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3921, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "current_qty" of relation "pos_order_line_canceled" does not exist
LINE 1: ...d" ("id", "user_id", "canceled_date", "order_id", "current_q...
                                                             ^

**Comment by 360org** [comment]
also, i try to install multi cancel it shows me something like that. 
![image](https://user-images.githubusercontent.com/8590556/31304751-9bef54a6-ab53-11e7-8d10-a1d781cf821d.png)

**Comment by ilmir-k** [comment]
Hi @W360S 

Please note that you don't need to use `pos_multi_session_restaurant_cancel_order` anymore, because we released new versions of pos_order_cancel_restaurant and pos_multi_session_restaurant, which are compatible without this module. So you can remove it.
After removing try to upgrade your system again. Actually, you should upgrade the modules pos_order_cancel_restaurant and pos_multi_session_restaurant.

**Comment by 360org** [comment]
@ilmir-k why when i install pos_order_cancel_restaurant it auto install pos_multi_session_restaurant_cancel_order?

**Comment by 360org** [comment]
and also the error comes when upgrade to the latest pos-addons code?

**Comment by ilmir-k** [comment]
@W360S 

It is strangely, because pos_multi_session_restaurant_cancel_order module is not dependency of pos_order_cancel_restaurant and moreover we removed this module from our repository.

It should be noted also that we added new module pos_restaurant_base in the dependencies instead.

Be sure that you have the latest commits 
https://github.com/it-projects-llc/pos-addons/commits/10.0/pos_order_cancel
https://github.com/it-projects-llc/pos-addons/commits/10.0/pos_order_cancel_restaurant

Anyway, we will check again the modules work

**Comment by 360org** [comment]
yeap, I can see I have already install both of them
