### ISSUE TITLE
10.0 - Error in pos_multi_session_restaurant

### ISSUE THREAD

**Issue by thomaspaulb** [itpp-labs/pos-addons#518]
The error that comes is:

```
Uncaught TypeError: Cannot read property 'id' of null
http://irodion.1systeem.nl/pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js:130
Traceback:
TypeError: Cannot read property 'id' of null
    at child.ms_on_update (http://irodion.1systeem.nl/pos_multi_session_restaurant/static/src/js/pos_multi_session_restaurant.js:130:38)
    at http://irodion.1systeem.nl/pos_multi_session/static/src/js/pos_multi_session.js:568:34
    at Array.forEach (<anonymous>)
    at Object.<anonymous> 
(http://irodion.1systeem.nl/pos_multi_session/static/src/js/pos_multi_session.js:567:32)
    at fire (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) 
 (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3321:62)
    at fire (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://irodion.1systeem.nl/web/static/lib/jquery/jquery.js:3283:104)
```

Line 130 contains:

```
if (order && order.table.id != data.table_id) {
    order.transfer = true;
    order.destroy({'reason': 'abandon'});
}
```

Seems that order.table is empty here.

**Comment by yelizariev** [comment]
fixed in 10.0 by @thomaspaulb
