### ISSUE TITLE
Trying to install, I get this error. Could you help?

### ISSUE THREAD

**Issue by lapagept** [itpp-labs/pos-addons#6]
2015-04-24 14:39:05,501 27075 INFO 03test openerp.modules.loading: loading product_variant_multi/product_view.xml
2015-04-24 14:39:05,906 27075 ERROR 03test openerp.addons.base.ir.ir_ui_view: Field `price_margin` does not exist

Error context:
View `product.variant.form`
[view_id: 2317, xml_id: n/a, model: product.product, parent_id: n/a]
2015-04-24 14:39:05,908 27075 ERROR 03test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo-test/odoo-test/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 562, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 299, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 791, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 395, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo-test/odoo-test/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo-test/odoo-test/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo-test/odoo-test/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo-test/odoo-test/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo-test/odoo-test/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo-test/odoo-test/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/odoo-test/odoo-test/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/ir/ir_model.py", line 1067, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/models.py", line 4007, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo-test/odoo-test/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/models.py", line 4198, in _create
    recs._validate_fields(vals)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/models.py", line 1282, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `price_margin` does not exist

Error context:
View `product.variant.form`
[view_id: 2317, xml_id: n/a, model: product.product, parent_id: n/a]" while parsing /home/odoo-test/odoo-test/addons/product_variant_multi/product_view.xml:262, near
<record id="product_variant_form_view" model="ir.ui.view">
            <field name="name">product.variant.form</field>
            <field name="model">product.product</field>
            <field name="arch" type="xml">
                <form string="Product Variant" version="7.0">
                    <sheet>
                        <div class="oe_title">
                            <label for="name"/>
                            <h1>
                                <field name="name" required="1"/>
                            </h1>
                            <label for="product_tmpl_id"/>
                            <h2>
                                <field name="product_tmpl_id"/>
                            </h2>
                        </div>
                        <group>
                            <field name="variants"/>
                            <field name="default_code"/>
                            <field name="active"/>
                        </group>
                        <notebook colspan="4">
                            <page string="Dimensions">
                                <separator string="Dimension Values" colspan="4"/>
                                <field name="dimension_value_ids" context="{'product_tmpl_id':product_tmpl_id}" nolabel="1" colspan="4"/>
                            </page>
                            <page string="Prices">
                                <group>
                                    <field name="list_price" string="Template Sale Price" readonly="1"/>
                                    <field name="price_margin"/>
                                    <field name="price_extra"/>
                                    <field name="cost_price_extra"/>
                                </group>
                            </page>
                        </notebook>
                    </sheet>
                </form>
            </field>
        </record>

**Comment by yelizariev** [comment]
It seems that product_variant_multi is obsolete and should be updated or deleted from 8.0 branch

**Comment by yelizariev** [comment]
The module was deleted
