### ISSUE TITLE
[11.0] pos_network_printer Thread related error on windows

### ISSUE THREAD

**Issue by eng-eslam-a-y** [itpp-labs/pos-addons#698]
i am always get the below error when im using pos_network_printer module on windows machine

"POST /hw_proxy/status_network_printers HTTP/1.1" 200 -
2018-05-31 08:01:53,173 6456 ERROR dbv11_pos odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\PROGRA~2\ODOO11~1.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hw_proxy\controllers\main.py", line 138, in status_json
    return self.get_status()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hw_proxy\controllers\main.py", line 41, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hw_escpos\controllers\main.py", line 117, in get_status
    self.push_task('status')
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hw_escpos\controllers\main.py", line 193, in push_task
    self.lockedstart()
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hw_escpos\controllers\main.py", line 99, in lockedstart
    self.daemon = True
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\threading.py", line 1141, in daemon
    raise RuntimeError("cannot set daemon status of active thread")

**Comment by GabbasovDinar** [comment]
Hello, @eng-eslam-a-y
Do you have the error without our module?
