### ISSUE TITLE
Uncaught TypeError: Cannot read property 'edition' of undefined ---  on hw_printer_network

### ISSUE THREAD

**Issue by chafarleston** [itpp-labs/pos-addons#927]
Error:
Uncaught TypeError: Cannot read property 'edition' of undefined

http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:4197
Rastreo de error:
TypeError: Cannot read property 'edition' of undefined
    at Class.<anonymous> (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:4197:471)
    at http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:19:183
    at Function._.each._.forEach (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:12:558)
    at Function._.filter._.select (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:19:144)
    at Class.<anonymous> (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:4197:425)
    at http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:802:681
    at fire (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:802:649)
    at Function.each (http://192.168.1.101:8070/web/content/310-a95e100/web.assets_common.js:625:767)

![image](https://user-images.githubusercontent.com/380774/53220482-c56c8900-3632-11e9-99c3-5478fc75d0aa.png)

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov Can you check it?
